/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdmissionPlugin : AdmissionPlugin represents an admission plugin



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdmissionPlugin {
    #[serde(rename = "fromVersion", skip_serializing_if = "Option::is_none")]
    pub from_version: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "plugin", skip_serializing_if = "Option::is_none")]
    pub plugin: Option<String>,
}

impl AdmissionPlugin {
    /// AdmissionPlugin represents an admission plugin
    pub fn new() -> AdmissionPlugin {
        AdmissionPlugin {
            from_version: None,
            name: None,
            plugin: None,
        }
    }
}


