/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AgentPoolOptionalSettings {
    /// NodeLabels - The node labels to be persisted across all nodes in agent pool.
    #[serde(rename = "nodeLabels", skip_serializing_if = "Option::is_none")]
    pub node_labels: Option<::std::collections::HashMap<String, String>>,
    /// NodeTaints - The taints added to new nodes during node pool create and scale. For example, key=value:NoSchedule. Placing custom taints on system pool is not supported(except 'CriticalAddonsOnly' taint or taint effect is 'PreferNoSchedule'). Please refer to https://aka.ms/aks/system-taints for detail
    #[serde(rename = "nodeTaints", skip_serializing_if = "Option::is_none")]
    pub node_taints: Option<Vec<String>>,
}

impl AgentPoolOptionalSettings {
    pub fn new() -> AgentPoolOptionalSettings {
        AgentPoolOptionalSettings {
            node_labels: None,
            node_taints: None,
        }
    }
}


