/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AlertmanagerSpec {
    /// Config contains the alertmanager configuration in YAML
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Vec<i32>>,
}

impl AlertmanagerSpec {
    pub fn new() -> AlertmanagerSpec {
        AlertmanagerSpec {
            config: None,
        }
    }
}


