/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AlibabaNodeSpec : AlibabaNodeSpec alibaba specific node settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AlibabaNodeSpec {
    #[serde(rename = "diskSize", skip_serializing_if = "Option::is_none")]
    pub disk_size: Option<String>,
    #[serde(rename = "diskType", skip_serializing_if = "Option::is_none")]
    pub disk_type: Option<String>,
    #[serde(rename = "instanceType", skip_serializing_if = "Option::is_none")]
    pub instance_type: Option<String>,
    #[serde(rename = "internetMaxBandwidthOut", skip_serializing_if = "Option::is_none")]
    pub internet_max_bandwidth_out: Option<String>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "vSwitchID", skip_serializing_if = "Option::is_none")]
    pub v_switch_id: Option<String>,
    #[serde(rename = "zoneID", skip_serializing_if = "Option::is_none")]
    pub zone_id: Option<String>,
}

impl AlibabaNodeSpec {
    /// AlibabaNodeSpec alibaba specific node settings
    pub fn new() -> AlibabaNodeSpec {
        AlibabaNodeSpec {
            disk_size: None,
            disk_type: None,
            instance_type: None,
            internet_max_bandwidth_out: None,
            labels: None,
            v_switch_id: None,
            zone_id: None,
        }
    }
}


