/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AlibabaInstanceType {
    #[serde(rename = "cpuCoreCount", skip_serializing_if = "Option::is_none")]
    pub cpu_core_count: Option<i64>,
    #[serde(rename = "gpuCoreCount", skip_serializing_if = "Option::is_none")]
    pub gpu_core_count: Option<i64>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "memorySize", skip_serializing_if = "Option::is_none")]
    pub memory_size: Option<f64>,
}

impl AlibabaInstanceType {
    pub fn new() -> AlibabaInstanceType {
        AlibabaInstanceType {
            cpu_core_count: None,
            gpu_core_count: None,
            id: None,
            memory_size: None,
        }
    }
}


