/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AnexiaNodeSpec : AnexiaNodeSpec anexia specific node settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AnexiaNodeSpec {
    /// CPUs states how many cpus the node will have.
    #[serde(rename = "cpus")]
    pub cpus: i64,
    /// DiskSize states the disk size that node will have.
    #[serde(rename = "diskSize")]
    pub disk_size: i64,
    /// Memory states the memory that node will have.
    #[serde(rename = "memory")]
    pub memory: i64,
    /// TemplateID instance template
    #[serde(rename = "templateID")]
    pub template_id: String,
    /// VlanID Instance vlanID
    #[serde(rename = "vlanID")]
    pub vlan_id: String,
}

impl AnexiaNodeSpec {
    /// AnexiaNodeSpec anexia specific node settings
    pub fn new(cpus: i64, disk_size: i64, memory: i64, template_id: String, vlan_id: String) -> AnexiaNodeSpec {
        AnexiaNodeSpec {
            cpus,
            disk_size,
            memory,
            template_id,
            vlan_id,
        }
    }
}


