/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationInstallationStatus {
    #[serde(rename = "applicationVersion", skip_serializing_if = "Option::is_none")]
    pub application_version: Option<Box<crate::models::ApplicationVersion>>,
    /// Conditions contains conditions an installation is in, its primary use case is status signaling between controllers or between controllers and the API
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::ApplicationInstallationCondition>>,
    /// +kubebuilder:validation:Enum=helm
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
}

impl ApplicationInstallationStatus {
    pub fn new() -> ApplicationInstallationStatus {
        ApplicationInstallationStatus {
            application_version: None,
            conditions: None,
            method: None,
        }
    }
}


