/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuditLoggingSettings {
    /// Enabled will enable or disable audit logging.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// AuditPolicyPreset refers to a pre-defined set of audit policy rules. Supported values are `metadata`, `recommended` and `minimal`. See KKP documentation for what each policy preset includes.
    #[serde(rename = "policyPreset", skip_serializing_if = "Option::is_none")]
    pub policy_preset: Option<String>,
    #[serde(rename = "sidecar", skip_serializing_if = "Option::is_none")]
    pub sidecar: Option<Box<crate::models::AuditSidecarSettings>>,
}

impl AuditLoggingSettings {
    pub fn new() -> AuditLoggingSettings {
        AuditLoggingSettings {
            enabled: None,
            policy_preset: None,
            sidecar: None,
        }
    }
}


