/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AzureSize {
    #[serde(rename = "maxDataDiskCount", skip_serializing_if = "Option::is_none")]
    pub max_data_disk_count: Option<i32>,
    #[serde(rename = "memoryInMB", skip_serializing_if = "Option::is_none")]
    pub memory_in_mb: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "numberOfCores", skip_serializing_if = "Option::is_none")]
    pub number_of_cores: Option<i32>,
    #[serde(rename = "numberOfGPUs", skip_serializing_if = "Option::is_none")]
    pub number_of_gpus: Option<i32>,
    #[serde(rename = "osDiskSizeInMB", skip_serializing_if = "Option::is_none")]
    pub os_disk_size_in_mb: Option<i32>,
    #[serde(rename = "resourceDiskSizeInMB", skip_serializing_if = "Option::is_none")]
    pub resource_disk_size_in_mb: Option<i32>,
}

impl AzureSize {
    pub fn new() -> AzureSize {
        AzureSize {
            max_data_disk_count: None,
            memory_in_mb: None,
            name: None,
            number_of_cores: None,
            number_of_gpus: None,
            os_disk_size_in_mb: None,
            resource_disk_size_in_mb: None,
        }
    }
}


