/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AzureRouteTablesList : AzureRouteTablesList is the object representing the route tables for vms in azure cloud provider



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AzureRouteTablesList {
    #[serde(rename = "routeTables", skip_serializing_if = "Option::is_none")]
    pub route_tables: Option<Vec<String>>,
}

impl AzureRouteTablesList {
    /// AzureRouteTablesList is the object representing the route tables for vms in azure cloud provider
    pub fn new() -> AzureRouteTablesList {
        AzureRouteTablesList {
            route_tables: None,
        }
    }
}


