/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AzureSecurityGroupsList : AzureSecurityGroupsList is the object representing the security groups for vms in azure cloud provider



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AzureSecurityGroupsList {
    #[serde(rename = "securityGroups", skip_serializing_if = "Option::is_none")]
    pub security_groups: Option<Vec<String>>,
}

impl AzureSecurityGroupsList {
    /// AzureSecurityGroupsList is the object representing the security groups for vms in azure cloud provider
    pub fn new() -> AzureSecurityGroupsList {
        AzureSecurityGroupsList {
            security_groups: None,
        }
    }
}


