/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AzureAvailabilityZonesList : AzureAvailabilityZonesList is the object representing the availability zones for vms in azure cloud provider



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AzureAvailabilityZonesList {
    #[serde(rename = "zones", skip_serializing_if = "Option::is_none")]
    pub zones: Option<Vec<String>>,
}

impl AzureAvailabilityZonesList {
    /// AzureAvailabilityZonesList is the object representing the availability zones for vms in azure cloud provider
    pub fn new() -> AzureAvailabilityZonesList {
        AzureAvailabilityZonesList {
            zones: None,
        }
    }
}


