/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BackupCredentials : BackupCredentials contains credentials for etcd backups



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BackupCredentials {
    /// Destination corresponds to the Seeds Seed.Spec.EtcdBackupRestore.Destinations, it defines for which destination the backup credentials will be created. If set, it updates the credentials ref in the related Seed BackupDestination
    #[serde(rename = "destination", skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    #[serde(rename = "s3", skip_serializing_if = "Option::is_none")]
    pub s3: Option<Box<crate::models::S3BackupCredentials>>,
}

impl BackupCredentials {
    /// BackupCredentials contains credentials for etcd backups
    pub fn new() -> BackupCredentials {
        BackupCredentials {
            destination: None,
            s3: None,
        }
    }
}


