/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ClusterRoleBinding {
    #[serde(rename = "roleRefName", skip_serializing_if = "Option::is_none")]
    pub role_ref_name: Option<String>,
    /// Subjects holds references to the objects the role applies to.
    #[serde(rename = "subjects", skip_serializing_if = "Option::is_none")]
    pub subjects: Option<Vec<crate::models::Subject>>,
}

impl ClusterRoleBinding {
    pub fn new() -> ClusterRoleBinding {
        ClusterRoleBinding {
            role_ref_name: None,
            subjects: None,
        }
    }
}


