/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ClusterRoleName : ClusterRoleName defines RBAC cluster role name object for the user cluster



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ClusterRoleName {
    /// Name of the cluster role.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ClusterRoleName {
    /// ClusterRoleName defines RBAC cluster role name object for the user cluster
    pub fn new() -> ClusterRoleName {
        ClusterRoleName {
            name: None,
        }
    }
}


