/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CniPluginSettings {
    /// Possible values are `canal`, `cilium` or `none`.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// Version defines the CNI plugin version to be used. This varies by chosen CNI plugin type.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl CniPluginSettings {
    pub fn new() -> CniPluginSettings {
        CniPluginSettings {
            _type: None,
            version: None,
        }
    }
}


