/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ControlPlaneMetrics : ControlPlaneMetrics defines a metric for the user cluster control plane resources



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ControlPlaneMetrics {
    /// CPUTotalMillicores in m cores
    #[serde(rename = "cpuTotalMillicores", skip_serializing_if = "Option::is_none")]
    pub cpu_total_millicores: Option<i64>,
    /// MemoryTotalBytes in bytes
    #[serde(rename = "memoryTotalBytes", skip_serializing_if = "Option::is_none")]
    pub memory_total_bytes: Option<i64>,
}

impl ControlPlaneMetrics {
    /// ControlPlaneMetrics defines a metric for the user cluster control plane resources
    pub fn new() -> ControlPlaneMetrics {
        ControlPlaneMetrics {
            cpu_total_millicores: None,
            memory_total_bytes: None,
        }
    }
}


