/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DatacenterSpecGcp {
    /// Region to use, for example \"europe-west3\", for a full list of regions see https://cloud.google.com/compute/docs/regions-zones/
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// Optional: Regional clusters spread their resources across multiple availability zones. Refer to the official documentation for more details on this: https://cloud.google.com/kubernetes-engine/docs/concepts/regional-clusters
    #[serde(rename = "regional", skip_serializing_if = "Option::is_none")]
    pub regional: Option<bool>,
    /// List of enabled zones, for example [a, c]. See the link above for the available zones in your chosen region.
    #[serde(rename = "zoneSuffixes", skip_serializing_if = "Option::is_none")]
    pub zone_suffixes: Option<Vec<String>>,
}

impl DatacenterSpecGcp {
    pub fn new() -> DatacenterSpecGcp {
        DatacenterSpecGcp {
            region: None,
            regional: None,
            zone_suffixes: None,
        }
    }
}


