/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DatacenterSpecAlibaba {
    /// Region to use, for a full list of regions see https://www.alibabacloud.com/help/doc-detail/40654.htm
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
}

impl DatacenterSpecAlibaba {
    pub fn new() -> DatacenterSpecAlibaba {
        DatacenterSpecAlibaba {
            region: None,
        }
    }
}


