/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DatacenterSpecPacket {
    /// The list of enabled facilities, for example \"ams1\", for a full list of available facilities see https://support.packet.com/kb/articles/data-centers
    #[serde(rename = "facilities", skip_serializing_if = "Option::is_none")]
    pub facilities: Option<Vec<String>>,
    /// Metros are facilities that are grouped together geographically and share capacity and networking features, see https://metal.equinix.com/developers/docs/locations/metros/
    #[serde(rename = "metro", skip_serializing_if = "Option::is_none")]
    pub metro: Option<String>,
}

impl DatacenterSpecPacket {
    pub fn new() -> DatacenterSpecPacket {
        DatacenterSpecPacket {
            facilities: None,
            metro: None,
        }
    }
}


