/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DatacenterSpecNutanix {
    /// Optional: AllowInsecure allows to disable the TLS certificate check against the endpoint (defaults to false)
    #[serde(rename = "allowInsecure", skip_serializing_if = "Option::is_none")]
    pub allow_insecure: Option<bool>,
    /// Endpoint to use for accessing Nutanix Prism Central. No protocol or port should be passed, for example \"nutanix.example.com\" or \"10.0.0.1\"
    #[serde(rename = "endpoint", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<::std::collections::HashMap<String, String>>,
    /// Optional: Port to use when connecting to the Nutanix Prism Central endpoint (defaults to 9440)
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
}

impl DatacenterSpecNutanix {
    pub fn new() -> DatacenterSpecNutanix {
        DatacenterSpecNutanix {
            allow_insecure: None,
            endpoint: None,
            images: None,
            port: None,
        }
    }
}


