/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DigitaloceanNodeSpec : DigitaloceanNodeSpec digitalocean node settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DigitaloceanNodeSpec {
    /// enable backups for the droplet
    #[serde(rename = "backups", skip_serializing_if = "Option::is_none")]
    pub backups: Option<bool>,
    /// DEPRECATED IPv6 is enabled automatically based on IP Family of the cluster so setting this field is not needed. enable ipv6 for the droplet
    #[serde(rename = "ipv6", skip_serializing_if = "Option::is_none")]
    pub ipv6: Option<bool>,
    /// enable monitoring for the droplet
    #[serde(rename = "monitoring", skip_serializing_if = "Option::is_none")]
    pub monitoring: Option<bool>,
    /// droplet size slug
    #[serde(rename = "size")]
    pub size: String,
    /// additional droplet tags
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl DigitaloceanNodeSpec {
    /// DigitaloceanNodeSpec digitalocean node settings
    pub fn new(size: String) -> DigitaloceanNodeSpec {
        DigitaloceanNodeSpec {
            backups: None,
            ipv6: None,
            monitoring: None,
            size,
            tags: None,
        }
    }
}


