/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EksNodegroupScalingConfig {
    /// The current number of nodes that the managed node group should maintain.
    #[serde(rename = "desiredSize", skip_serializing_if = "Option::is_none")]
    pub desired_size: Option<i64>,
    /// The maximum number of nodes that the managed node group can scale out to. For information about the maximum number that you can specify, see Amazon EKS service quotas (https://docs.aws.amazon.com/eks/latest/userguide/service-quotas.html) in the Amazon EKS User Guide.
    #[serde(rename = "maxSize", skip_serializing_if = "Option::is_none")]
    pub max_size: Option<i64>,
    /// The minimum number of nodes that the managed node group can scale in to. This number must be greater than zero.
    #[serde(rename = "minSize", skip_serializing_if = "Option::is_none")]
    pub min_size: Option<i64>,
}

impl EksNodegroupScalingConfig {
    pub fn new() -> EksNodegroupScalingConfig {
        EksNodegroupScalingConfig {
            desired_size: None,
            max_size: None,
            min_size: None,
        }
    }
}


