/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EventRateLimitConfigItem {
    #[serde(rename = "burst", skip_serializing_if = "Option::is_none")]
    pub burst: Option<i32>,
    #[serde(rename = "cacheSize", skip_serializing_if = "Option::is_none")]
    pub cache_size: Option<i32>,
    #[serde(rename = "qps", skip_serializing_if = "Option::is_none")]
    pub qps: Option<i32>,
}

impl EventRateLimitConfigItem {
    pub fn new() -> EventRateLimitConfigItem {
        EventRateLimitConfigItem {
            burst: None,
            cache_size: None,
            qps: None,
        }
    }
}


