/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GatekeeperConfigSpec {
    /// Configuration for namespace exclusion
    #[serde(rename = "match", skip_serializing_if = "Option::is_none")]
    pub _match: Option<Vec<crate::models::MatchEntry>>,
    #[serde(rename = "readiness", skip_serializing_if = "Option::is_none")]
    pub readiness: Option<Box<crate::models::ReadinessSpec>>,
    #[serde(rename = "sync", skip_serializing_if = "Option::is_none")]
    pub sync: Option<Box<crate::models::Sync>>,
    #[serde(rename = "validation", skip_serializing_if = "Option::is_none")]
    pub validation: Option<Box<crate::models::Validation>>,
}

impl GatekeeperConfigSpec {
    pub fn new() -> GatekeeperConfigSpec {
        GatekeeperConfigSpec {
            _match: None,
            readiness: None,
            sync: None,
            validation: None,
        }
    }
}


