/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GkeMachineDeploymentCloudSpec {
    #[serde(rename = "autoscaling", skip_serializing_if = "Option::is_none")]
    pub autoscaling: Option<Box<crate::models::GkeNodePoolAutoscaling>>,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Box<crate::models::GkeNodeConfig>>,
    /// Locations: The list of Google Compute Engine zones (https://cloud.google.com/compute/docs/zones#available) in which the NodePool's nodes should be located. If this value is unspecified during node pool creation, the Cluster.Locations (https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.FIELDS.locations) value will be used, instead. Warning: changing node pool locations will result in nodes being added and/or removed.
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<String>>,
    #[serde(rename = "management", skip_serializing_if = "Option::is_none")]
    pub management: Option<Box<crate::models::GkeNodeManagement>>,
}

impl GkeMachineDeploymentCloudSpec {
    pub fn new() -> GkeMachineDeploymentCloudSpec {
        GkeMachineDeploymentCloudSpec {
            autoscaling: None,
            config: None,
            locations: None,
            management: None,
        }
    }
}


