/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GkeNodeManagement : GKENodeManagement defines the set of node management services turned on for the node pool.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GkeNodeManagement {
    /// AutoRepair: A flag that specifies whether the node auto-repair is enabled for the node pool. If enabled, the nodes in this node pool will be monitored and, if they fail health checks too many times, an automatic repair action will be triggered.
    #[serde(rename = "autoRepair", skip_serializing_if = "Option::is_none")]
    pub auto_repair: Option<bool>,
    /// AutoUpgrade: A flag that specifies whether node auto-upgrade is enabled for the node pool. If enabled, node auto-upgrade helps keep the nodes in your node pool up to date with the latest release version of Kubernetes.
    #[serde(rename = "autoUpgrade", skip_serializing_if = "Option::is_none")]
    pub auto_upgrade: Option<bool>,
}

impl GkeNodeManagement {
    /// GKENodeManagement defines the set of node management services turned on for the node pool.
    pub fn new() -> GkeNodeManagement {
        GkeNodeManagement {
            auto_repair: None,
            auto_upgrade: None,
        }
    }
}


