/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GkeShieldedInstanceConfig {
    /// EnableIntegrityMonitoring: Defines whether the instance has integrity monitoring enabled. Enables monitoring and attestation of the boot integrity of the instance. The attestation is performed against the integrity policy baseline. This baseline is initially derived from the implicitly trusted boot image when the instance is created.
    #[serde(rename = "enableIntegrityMonitoring", skip_serializing_if = "Option::is_none")]
    pub enable_integrity_monitoring: Option<bool>,
    /// EnableSecureBoot: Defines whether the instance has Secure Boot enabled. Secure Boot helps ensure that the system only runs authentic software by verifying the digital signature of all boot components, and halting the boot process if signature verification fails.
    #[serde(rename = "enableSecureBoot", skip_serializing_if = "Option::is_none")]
    pub enable_secure_boot: Option<bool>,
}

impl GkeShieldedInstanceConfig {
    pub fn new() -> GkeShieldedInstanceConfig {
        GkeShieldedInstanceConfig {
            enable_integrity_monitoring: None,
            enable_secure_boot: None,
        }
    }
}


