/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HelmCredentials {
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<Box<crate::models::SecretKeySelector>>,
    #[serde(rename = "registryConfigFile", skip_serializing_if = "Option::is_none")]
    pub registry_config_file: Option<Box<crate::models::SecretKeySelector>>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<Box<crate::models::SecretKeySelector>>,
}

impl HelmCredentials {
    pub fn new() -> HelmCredentials {
        HelmCredentials {
            password: None,
            registry_config_file: None,
            username: None,
        }
    }
}


