/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IpamPool {
    #[serde(rename = "datacenters", skip_serializing_if = "Option::is_none")]
    pub datacenters: Option<::std::collections::HashMap<String, crate::models::IpamPoolDatacenterSettings>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl IpamPool {
    pub fn new() -> IpamPool {
        IpamPool {
            datacenters: None,
            name: None,
        }
    }
}


