/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JsonSchemaPropsOrArray : JSONSchemaPropsOrArray represents a value that can either be a JSONSchemaProps or an array of JSONSchemaProps. Mainly here for serialization purposes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JsonSchemaPropsOrArray {
    #[serde(rename = "JSONSchemas", skip_serializing_if = "Option::is_none")]
    pub json_schemas: Option<Vec<crate::models::JsonSchemaProps>>,
    #[serde(rename = "Schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<Box<crate::models::JsonSchemaProps>>,
}

impl JsonSchemaPropsOrArray {
    /// JSONSchemaPropsOrArray represents a value that can either be a JSONSchemaProps or an array of JSONSchemaProps. Mainly here for serialization purposes.
    pub fn new() -> JsonSchemaPropsOrArray {
        JsonSchemaPropsOrArray {
            json_schemas: None,
            schema: None,
        }
    }
}


