/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JsonSchemaPropsOrStringArray {
    #[serde(rename = "Property", skip_serializing_if = "Option::is_none")]
    pub property: Option<Vec<String>>,
    #[serde(rename = "Schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<Box<crate::models::JsonSchemaProps>>,
}

impl JsonSchemaPropsOrStringArray {
    pub fn new() -> JsonSchemaPropsOrStringArray {
        JsonSchemaPropsOrStringArray {
            property: None,
            schema: None,
        }
    }
}


