/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Kind {
    /// APIGroups specifies the APIGroups of the resources
    #[serde(rename = "apiGroups", skip_serializing_if = "Option::is_none")]
    pub api_groups: Option<Vec<String>>,
    /// Kinds specifies the kinds of the resources
    #[serde(rename = "kinds", skip_serializing_if = "Option::is_none")]
    pub kinds: Option<Vec<String>>,
}

impl Kind {
    pub fn new() -> Kind {
        Kind {
            api_groups: None,
            kinds: None,
        }
    }
}


