/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KubeOneDigitalOceanCloudSpec {
    /// Token is used to authenticate with the DigitalOcean API.
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl KubeOneDigitalOceanCloudSpec {
    pub fn new() -> KubeOneDigitalOceanCloudSpec {
        KubeOneDigitalOceanCloudSpec {
            token: None,
        }
    }
}


