/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KubevirtCloudSpec {
    #[serde(rename = "credentialsReference", skip_serializing_if = "Option::is_none")]
    pub credentials_reference: Option<Box<crate::models::GlobalObjectKeySelector>>,
    #[serde(rename = "csiKubeconfig", skip_serializing_if = "Option::is_none")]
    pub csi_kubeconfig: Option<String>,
    /// InfraStorageClasses is a list of storage classes from KubeVirt infra cluster that are used for initialization of user cluster storage classes by the CSI driver kubevirt (hot pluggable disks)
    #[serde(rename = "infraStorageClasses", skip_serializing_if = "Option::is_none")]
    pub infra_storage_classes: Option<Vec<String>>,
    /// The cluster's kubeconfig file, encoded with base64.
    #[serde(rename = "kubeconfig", skip_serializing_if = "Option::is_none")]
    pub kubeconfig: Option<String>,
    /// PreAllocatedDataVolumes holds list of preallocated DataVolumes which can be used as reference for DataVolume cloning.
    #[serde(rename = "preAllocatedDataVolumes", skip_serializing_if = "Option::is_none")]
    pub pre_allocated_data_volumes: Option<Vec<crate::models::PreAllocatedDataVolume>>,
}

impl KubevirtCloudSpec {
    pub fn new() -> KubevirtCloudSpec {
        KubevirtCloudSpec {
            credentials_reference: None,
            csi_kubeconfig: None,
            infra_storage_classes: None,
            kubeconfig: None,
            pre_allocated_data_volumes: None,
        }
    }
}


