/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KubeOneNutanixCloudSpec {
    #[serde(rename = "allowInsecure", skip_serializing_if = "Option::is_none")]
    pub allow_insecure: Option<bool>,
    /// ClusterName is the Nutanix cluster that this user cluster will be deployed to. +optional
    #[serde(rename = "clusterName", skip_serializing_if = "Option::is_none")]
    pub cluster_name: Option<String>,
    /// PrismElementEndpoint to access Nutanix Prism Element for the CSI driver
    #[serde(rename = "elementEndpoint", skip_serializing_if = "Option::is_none")]
    pub element_endpoint: Option<String>,
    /// PrismElementPassword to be used for the CSI driver
    #[serde(rename = "elementPassword", skip_serializing_if = "Option::is_none")]
    pub element_password: Option<String>,
    /// PrismElementUsername to be used for the CSI driver
    #[serde(rename = "elementUsername", skip_serializing_if = "Option::is_none")]
    pub element_username: Option<String>,
    /// Endpoint is the Nutanix API (Prism Central) endpoint
    #[serde(rename = "endpoint", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Port is the Nutanix API (Prism Central) port
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<String>,
    #[serde(rename = "proxyURL", skip_serializing_if = "Option::is_none")]
    pub proxy_url: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl KubeOneNutanixCloudSpec {
    pub fn new() -> KubeOneNutanixCloudSpec {
        KubeOneNutanixCloudSpec {
            allow_insecure: None,
            cluster_name: None,
            element_endpoint: None,
            element_password: None,
            element_username: None,
            endpoint: None,
            password: None,
            port: None,
            proxy_url: None,
            username: None,
        }
    }
}


