/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KubeOneVMwareCloudDirectorCloudSpec {
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "vdc", skip_serializing_if = "Option::is_none")]
    pub vdc: Option<String>,
}

impl KubeOneVMwareCloudDirectorCloudSpec {
    pub fn new() -> KubeOneVMwareCloudDirectorCloudSpec {
        KubeOneVMwareCloudDirectorCloudSpec {
            organization: None,
            password: None,
            url: None,
            username: None,
            vdc: None,
        }
    }
}


