/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MachineDeploymentVmResourceQuota {
    #[serde(rename = "enableGPU", skip_serializing_if = "Option::is_none")]
    pub enable_gpu: Option<bool>,
    /// Maximal number of vCPU
    #[serde(rename = "maxCPU", skip_serializing_if = "Option::is_none")]
    pub max_cpu: Option<i64>,
    /// Maximum RAM size in GB
    #[serde(rename = "maxRAM", skip_serializing_if = "Option::is_none")]
    pub max_ram: Option<i64>,
    /// Minimal number of vCPU
    #[serde(rename = "minCPU", skip_serializing_if = "Option::is_none")]
    pub min_cpu: Option<i64>,
    /// Minimal RAM size in GB
    #[serde(rename = "minRAM", skip_serializing_if = "Option::is_none")]
    pub min_ram: Option<i64>,
}

impl MachineDeploymentVmResourceQuota {
    pub fn new() -> MachineDeploymentVmResourceQuota {
        MachineDeploymentVmResourceQuota {
            enable_gpu: None,
            max_cpu: None,
            max_ram: None,
            min_cpu: None,
            min_ram: None,
        }
    }
}


