/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MeteringReport : MeteringReport holds objects names and metadata for available reports



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MeteringReport {
    #[serde(rename = "lastModified", skip_serializing_if = "Option::is_none")]
    pub last_modified: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
}

impl MeteringReport {
    /// MeteringReport holds objects names and metadata for available reports
    pub fn new() -> MeteringReport {
        MeteringReport {
            last_modified: None,
            name: None,
            size: None,
        }
    }
}


