/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MlaAdminSetting {
    #[serde(rename = "loggingRateLimits", skip_serializing_if = "Option::is_none")]
    pub logging_rate_limits: Option<Box<crate::models::LoggingRateLimitSettings>>,
    #[serde(rename = "monitoringRateLimits", skip_serializing_if = "Option::is_none")]
    pub monitoring_rate_limits: Option<Box<crate::models::MonitoringRateLimitSettings>>,
}

impl MlaAdminSetting {
    pub fn new() -> MlaAdminSetting {
        MlaAdminSetting {
            logging_rate_limits: None,
            monitoring_rate_limits: None,
        }
    }
}


