/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NetworkDefaultsIpFamily {
    /// NodeCIDRMaskSize contains the default mask size used to address the nodes within provided Pods CIDR.
    #[serde(rename = "nodeCidrMaskSize", skip_serializing_if = "Option::is_none")]
    pub node_cidr_mask_size: Option<i32>,
    /// NodePortsAllowedIPRange defines the default IP range from which access to NodePort services is allowed for applicable cloud providers.
    #[serde(rename = "nodePortsAllowedIPRange", skip_serializing_if = "Option::is_none")]
    pub node_ports_allowed_ip_range: Option<String>,
    /// PodsCIDR contains the default network range from which POD networks are allocated.
    #[serde(rename = "podsCidr", skip_serializing_if = "Option::is_none")]
    pub pods_cidr: Option<String>,
    /// ServicesCIDR contains the default network range from which service VIPs are allocated.
    #[serde(rename = "servicesCidr", skip_serializing_if = "Option::is_none")]
    pub services_cidr: Option<String>,
}

impl NetworkDefaultsIpFamily {
    pub fn new() -> NetworkDefaultsIpFamily {
        NetworkDefaultsIpFamily {
            node_cidr_mask_size: None,
            node_ports_allowed_ip_range: None,
            pods_cidr: None,
            services_cidr: None,
        }
    }
}


