/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NodeVersionInfo : NodeVersionInfo node version information



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NodeVersionInfo {
    #[serde(rename = "kubelet", skip_serializing_if = "Option::is_none")]
    pub kubelet: Option<String>,
}

impl NodeVersionInfo {
    /// NodeVersionInfo node version information
    pub fn new() -> NodeVersionInfo {
        NodeVersionInfo {
            kubelet: None,
        }
    }
}


