/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NodeSettings {
    #[serde(rename = "containerdRegistryMirrors", skip_serializing_if = "Option::is_none")]
    pub containerd_registry_mirrors: Option<Box<crate::models::ContainerRuntimeContainerd>>,
    #[serde(rename = "httpProxy", skip_serializing_if = "Option::is_none")]
    pub http_proxy: Option<String>,
    /// Optional: These image registries will be configured as insecure on the container runtime.
    #[serde(rename = "insecureRegistries", skip_serializing_if = "Option::is_none")]
    pub insecure_registries: Option<Vec<String>>,
    #[serde(rename = "noProxy", skip_serializing_if = "Option::is_none")]
    pub no_proxy: Option<String>,
    /// Optional: Translates to --pod-infra-container-image on the kubelet. If not set, the kubelet will default it.
    #[serde(rename = "pauseImage", skip_serializing_if = "Option::is_none")]
    pub pause_image: Option<String>,
    /// Optional: These image registries will be configured as registry mirrors on the container runtime.
    #[serde(rename = "registryMirrors", skip_serializing_if = "Option::is_none")]
    pub registry_mirrors: Option<Vec<String>>,
}

impl NodeSettings {
    pub fn new() -> NodeSettings {
        NodeSettings {
            containerd_registry_mirrors: None,
            http_proxy: None,
            insecure_registries: None,
            no_proxy: None,
            pause_image: None,
            registry_mirrors: None,
        }
    }
}


