/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NodeSystemInfo {
    #[serde(rename = "architecture", skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,
    #[serde(rename = "containerRuntime", skip_serializing_if = "Option::is_none")]
    pub container_runtime: Option<String>,
    #[serde(rename = "containerRuntimeVersion", skip_serializing_if = "Option::is_none")]
    pub container_runtime_version: Option<String>,
    #[serde(rename = "kernelVersion", skip_serializing_if = "Option::is_none")]
    pub kernel_version: Option<String>,
    #[serde(rename = "kubeletVersion", skip_serializing_if = "Option::is_none")]
    pub kubelet_version: Option<String>,
    #[serde(rename = "operatingSystem", skip_serializing_if = "Option::is_none")]
    pub operating_system: Option<String>,
}

impl NodeSystemInfo {
    pub fn new() -> NodeSystemInfo {
        NodeSystemInfo {
            architecture: None,
            container_runtime: None,
            container_runtime_version: None,
            kernel_version: None,
            kubelet_version: None,
            operating_system: None,
        }
    }
}


