/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NutanixCategory {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "systemDefined", skip_serializing_if = "Option::is_none")]
    pub system_defined: Option<bool>,
}

impl NutanixCategory {
    pub fn new() -> NutanixCategory {
        NutanixCategory {
            description: None,
            name: None,
            system_defined: None,
        }
    }
}


