/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NutanixCsiConfig {
    /// Prism Element Endpoint to access Nutanix Prism Element for csi driver
    #[serde(rename = "endpoint", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    /// Optional: defaults to \"xfs\" +optional
    #[serde(rename = "fstype", skip_serializing_if = "Option::is_none")]
    pub fstype: Option<String>,
    /// Prism Element Password for csi driver
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Optional: Port to use when connecting to the Nutanix Prism Element endpoint (defaults to 9440) +optional
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// Optional: defaults to \"false\" +optional
    #[serde(rename = "ssSegmentedIscsiNetwork", skip_serializing_if = "Option::is_none")]
    pub ss_segmented_iscsi_network: Option<bool>,
    /// Optional: defaults to \"SelfServiceContainer\" +optional
    #[serde(rename = "storageContainer", skip_serializing_if = "Option::is_none")]
    pub storage_container: Option<String>,
    /// Prism Element Username for csi driver
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl NutanixCsiConfig {
    pub fn new() -> NutanixCsiConfig {
        NutanixCsiConfig {
            endpoint: None,
            fstype: None,
            password: None,
            port: None,
            ss_segmented_iscsi_network: None,
            storage_container: None,
            username: None,
        }
    }
}


