/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenstackSubnet {
    /// Id uniquely identifies the subnet
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// IPversion is the IP protocol version (4 or 6)
    #[serde(rename = "ipVersion", skip_serializing_if = "Option::is_none")]
    pub ip_version: Option<i64>,
    /// Name is human-readable name for the subnet
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl OpenstackSubnet {
    pub fn new() -> OpenstackSubnet {
        OpenstackSubnet {
            id: None,
            ip_version: None,
            name: None,
        }
    }
}


