/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenstackSubnetPool {
    /// Id uniquely identifies the subnet pool
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// IPversion is the IP protocol version (4 or 6)
    #[serde(rename = "ipVersion", skip_serializing_if = "Option::is_none")]
    pub ip_version: Option<i64>,
    /// IsDefault indicates if the subnetpool is default pool or not
    #[serde(rename = "isDefault", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    /// Name is the name of the subnet pool
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Prefixes is the list of subnet prefixes
    #[serde(rename = "prefixes", skip_serializing_if = "Option::is_none")]
    pub prefixes: Option<Vec<String>>,
}

impl OpenstackSubnetPool {
    pub fn new() -> OpenstackSubnetPool {
        OpenstackSubnetPool {
            id: None,
            ip_version: None,
            is_default: None,
            name: None,
            prefixes: None,
        }
    }
}


