/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenstackSize {
    /// Disk is the amount of root disk, measured in GB
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<i64>,
    /// IsPublic indicates whether the size is public (available to all projects) or scoped to a set of projects
    #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    /// MemoryTotalBytes is the amount of memory, measured in MB
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<i64>,
    /// Region specifies the geographic region in which the size resides
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// Slug holds  the name of the size
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// Swap is the amount of swap space, measured in MB
    #[serde(rename = "swap", skip_serializing_if = "Option::is_none")]
    pub swap: Option<i64>,
    /// VCPUs indicates how many (virtual) CPUs are available for this flavor
    #[serde(rename = "vcpus", skip_serializing_if = "Option::is_none")]
    pub vcpus: Option<i64>,
}

impl OpenstackSize {
    pub fn new() -> OpenstackSize {
        OpenstackSize {
            disk: None,
            is_public: None,
            memory: None,
            region: None,
            slug: None,
            swap: None,
            vcpus: None,
        }
    }
}


