/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenstackNodeSizeRequirements {
    /// MinimumMemory is the minimum required amount of memory, measured in MB
    #[serde(rename = "minimumMemory", skip_serializing_if = "Option::is_none")]
    pub minimum_memory: Option<i64>,
    /// VCPUs is the minimum required amount of (virtual) CPUs
    #[serde(rename = "minimumVCPUs", skip_serializing_if = "Option::is_none")]
    pub minimum_vcpus: Option<i64>,
}

impl OpenstackNodeSizeRequirements {
    pub fn new() -> OpenstackNodeSizeRequirements {
        OpenstackNodeSizeRequirements {
            minimum_memory: None,
            minimum_vcpus: None,
        }
    }
}


