/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PacketSize {
    #[serde(rename = "cpus", skip_serializing_if = "Option::is_none")]
    pub cpus: Option<Vec<crate::models::PacketCpu>>,
    #[serde(rename = "drives", skip_serializing_if = "Option::is_none")]
    pub drives: Option<Vec<crate::models::PacketDrive>>,
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl PacketSize {
    pub fn new() -> PacketSize {
        PacketSize {
            cpus: None,
            drives: None,
            memory: None,
            name: None,
        }
    }
}


