/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PacketNodeSpec : PacketNodeSpec specifies packet specific node settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PacketNodeSpec {
    /// InstanceType denotes the plan to which the device will be provisioned.
    #[serde(rename = "instanceType")]
    pub instance_type: String,
    /// additional instance tags
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl PacketNodeSpec {
    /// PacketNodeSpec specifies packet specific node settings
    pub fn new(instance_type: String) -> PacketNodeSpec {
        PacketNodeSpec {
            instance_type,
            tags: None,
        }
    }
}


