/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PresetBody : PresetBody represents the body of a created preset



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PresetBody {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "spec", skip_serializing_if = "Option::is_none")]
    pub spec: Option<Box<crate::models::PresetSpec>>,
}

impl PresetBody {
    /// PresetBody represents the body of a created preset
    pub fn new() -> PresetBody {
        PresetBody {
            name: None,
            spec: None,
        }
    }
}


