/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PresetList : PresetList represents a list of presets



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PresetList {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::Preset>>,
}

impl PresetList {
    /// PresetList represents a list of presets
    pub fn new() -> PresetList {
        PresetList {
            items: None,
        }
    }
}


