/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Preset : Preset represents a preset



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Preset {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "providers", skip_serializing_if = "Option::is_none")]
    pub providers: Option<Vec<crate::models::PresetProvider>>,
}

impl Preset {
    /// Preset represents a preset
    pub fn new() -> Preset {
        Preset {
            enabled: None,
            name: None,
            providers: None,
        }
    }
}


