/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProjectGroup : ProjectGroup is a helper data structure that stores the information about a project and a group prefix that a user belongs to.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectGroup {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl ProjectGroup {
    /// ProjectGroup is a helper data structure that stores the information about a project and a group prefix that a user belongs to.
    pub fn new() -> ProjectGroup {
        ProjectGroup {
            group: None,
            id: None,
        }
    }
}


