/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProxySettings : ProxySettings allow configuring a HTTP proxy for the controlplanes and nodes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProxySettings {
    #[serde(rename = "httpProxy", skip_serializing_if = "Option::is_none")]
    pub http_proxy: Option<String>,
    #[serde(rename = "noProxy", skip_serializing_if = "Option::is_none")]
    pub no_proxy: Option<String>,
}

impl ProxySettings {
    /// ProxySettings allow configuring a HTTP proxy for the controlplanes and nodes.
    pub fn new() -> ProxySettings {
        ProxySettings {
            http_proxy: None,
            no_proxy: None,
        }
    }
}


