/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RhelSpec : RHELSpec contains rhel specific settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RhelSpec {
    /// do a dist-upgrade on boot and reboot it required afterwards
    #[serde(rename = "distUpgradeOnBoot", skip_serializing_if = "Option::is_none")]
    pub dist_upgrade_on_boot: Option<bool>,
    #[serde(rename = "rhelSubscriptionManagerPassword", skip_serializing_if = "Option::is_none")]
    pub rhel_subscription_manager_password: Option<String>,
    #[serde(rename = "rhelSubscriptionManagerUser", skip_serializing_if = "Option::is_none")]
    pub rhel_subscription_manager_user: Option<String>,
    #[serde(rename = "rhsmOfflineToken", skip_serializing_if = "Option::is_none")]
    pub rhsm_offline_token: Option<String>,
}

impl RhelSpec {
    /// RHELSpec contains rhel specific settings
    pub fn new() -> RhelSpec {
        RhelSpec {
            dist_upgrade_on_boot: None,
            rhel_subscription_manager_password: None,
            rhel_subscription_manager_user: None,
            rhsm_offline_token: None,
        }
    }
}


