/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoleUser : RoleUser defines associated user with role



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoleUser {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(rename = "userEmail", skip_serializing_if = "Option::is_none")]
    pub user_email: Option<String>,
}

impl RoleUser {
    /// RoleUser defines associated user with role
    pub fn new() -> RoleUser {
        RoleUser {
            group: None,
            user_email: None,
        }
    }
}


