/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SecretKeySelector : +structType=atomic



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecretKeySelector {
    /// The key of the secret to select from.  Must be a valid secret key.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid? +optional
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined +optional
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

impl SecretKeySelector {
    /// +structType=atomic
    pub fn new() -> SecretKeySelector {
        SecretKeySelector {
            key: None,
            name: None,
            optional: None,
        }
    }
}


