/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Sync {
    /// If non-empty, entries on this list will be replicated into OPA
    #[serde(rename = "syncOnly", skip_serializing_if = "Option::is_none")]
    pub sync_only: Option<Vec<crate::models::Gvk>>,
}

impl Sync {
    pub fn new() -> Sync {
        Sync {
            sync_only: None,
        }
    }
}


