/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Target {
    #[serde(rename = "libs", skip_serializing_if = "Option::is_none")]
    pub libs: Option<Vec<String>>,
    #[serde(rename = "rego", skip_serializing_if = "Option::is_none")]
    pub rego: Option<String>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
}

impl Target {
    pub fn new() -> Target {
        Target {
            libs: None,
            rego: None,
            target: None,
        }
    }
}


