/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UbuntuSpec : UbuntuSpec ubuntu specific settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UbuntuSpec {
    /// do a dist-upgrade on boot and reboot it required afterwards
    #[serde(rename = "distUpgradeOnBoot", skip_serializing_if = "Option::is_none")]
    pub dist_upgrade_on_boot: Option<bool>,
}

impl UbuntuSpec {
    /// UbuntuSpec ubuntu specific settings
    pub fn new() -> UbuntuSpec {
        UbuntuSpec {
            dist_upgrade_on_boot: None,
        }
    }
}


