/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpdateWindow : This is only applied to cluster nodes using Flatcar Linux. The reference time for this is the node system time and might differ from the user's timezone, which needs to be considered when configuring a window.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateWindow {
    /// Sets the length of the update window beginning with the start time. This needs to be a valid duration as parsed by Go's time.ParseDuration (https://pkg.go.dev/time#ParseDuration), e.g. `2h`.
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<String>,
    /// Sets the start time of the update window. This can be a time of day in 24h format, e.g. `22:30`, or a day of week plus a time of day, for example `Mon 21:00`. Only short names for week days are supported, i.e. `Mon`, `Tue`, `Wed`, `Thu`, `Fri`, `Sat` and `Sun`.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
}

impl UpdateWindow {
    /// This is only applied to cluster nodes using Flatcar Linux. The reference time for this is the node system time and might differ from the user's timezone, which needs to be considered when configuring a window.
    pub fn new() -> UpdateWindow {
        UpdateWindow {
            length: None,
            start: None,
        }
    }
}


