/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V2QuotasBody {
    #[serde(rename = "quota", skip_serializing_if = "Option::is_none")]
    pub quota: Option<Box<crate::models::Quota>>,
    #[serde(rename = "subjectKind", skip_serializing_if = "Option::is_none")]
    pub subject_kind: Option<String>,
    #[serde(rename = "subjectName", skip_serializing_if = "Option::is_none")]
    pub subject_name: Option<String>,
}

impl V2QuotasBody {
    pub fn new() -> V2QuotasBody {
        V2QuotasBody {
            quota: None,
            subject_kind: None,
            subject_name: None,
        }
    }
}


