/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VSphereNetwork {
    /// AbsolutePath is the absolute path inside vCenter
    #[serde(rename = "absolutePath", skip_serializing_if = "Option::is_none")]
    pub absolute_path: Option<String>,
    /// Name is the name of the network
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// RelativePath is the relative path inside the datacenter
    #[serde(rename = "relativePath", skip_serializing_if = "Option::is_none")]
    pub relative_path: Option<String>,
    /// Type defines the type of network
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl VSphereNetwork {
    pub fn new() -> VSphereNetwork {
        VSphereNetwork {
            absolute_path: None,
            name: None,
            relative_path: None,
            _type: None,
        }
    }
}


