/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VersionList : VersionList represents a list of versions



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VersionList {
}

impl VersionList {
    /// VersionList represents a list of versions
    pub fn new() -> VersionList {
        VersionList {
        }
    }
}


