/*
 * Kubermatic Kubernetes Platform API
 *
 * This spec describes possible operations which can be made against the Kubermatic Kubernetes Platform API.
 *
 * The version of the OpenAPI document: 2.21
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VirtualMachineInstancePreset : VirtualMachineInstancePreset represents a KubeVirt Virtual Machine Instance Preset



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualMachineInstancePreset {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// Spec contains the kubevirtv1.VirtualMachineInstancePreset.Spec object marshalled
    #[serde(rename = "spec", skip_serializing_if = "Option::is_none")]
    pub spec: Option<String>,
}

impl VirtualMachineInstancePreset {
    /// VirtualMachineInstancePreset represents a KubeVirt Virtual Machine Instance Preset
    pub fn new() -> VirtualMachineInstancePreset {
        VirtualMachineInstancePreset {
            name: None,
            namespace: None,
            spec: None,
        }
    }
}


